{{- if (and .Values.config.mongodb.internal (not (and (eq .Values.config.mongodb.terminationPolicy "Pause") .Values.config.mongodb.pause))) }}
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.mongodb.version | quote }}
  databaseSecret:
    secretName: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
  {{- if .Values.config.mongodb.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  sslMode: disabled
  # clusterAuthMode: x509
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if .Values.config.mongodb.shardTopology.enabled }}
  shardTopology:
    configServer:
      prefix: configServer
      replicas: {{ .Values.config.mongodb.shardTopology.configServer.replicas }}
      configSource:
        configMap:
          name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
      podTemplate:
        {{- if .Values.persistence.velero.enabled }}
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
        {{- end }}
        spec:
          resources:
{{ toYaml .Values.config.mongodb.shardTopology.configServer.resources | indent 12 }}
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
    mongos:
      prefix: mongos
      replicas: {{ .Values.config.mongodb.shardTopology.mongos.replicas }}
      strategy:
        type: {{ (eq .Values.config.updateStrategy "Recreate") | ternary "RollingUpdate" .Values.config.updateStrategy }}
      configSource:
        configMap:
          name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
      podTemplate:
        {{- if .Values.persistence.velero.enabled }}
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
        {{- end }}
        spec:
          resources:
{{ toYaml .Values.config.mongodb.shardTopology.mongos.resources | indent 12 }}
    shard:
      prefix: shard
      replicas: {{ .Values.config.mongodb.shardTopology.shard.replicas }}
      shards: {{ .Values.config.mongodb.shardTopology.shard.shards }}
      configSource:
        configMap:
          name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
      podTemplate:
        {{- if .Values.persistence.velero.enabled }}
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
        {{- end }}
        spec:
          resources:
{{ toYaml .Values.config.mongodb.shardTopology.shard.resources | indent 12 }}
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
  {{- else }}
  configSource:
    configMap:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  {{- if .Values.config.mongodb.replicaSet.enabled }}
  replicas: {{ .Values.config.mongodb.replicas }}
  replicaSet:
    name: rs0
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- end }}
  podTemplate:
    {{- if .Values.persistence.velero.enabled }}
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
    {{- end }}
    spec:
      resources:
{{ toYaml .Values.config.mongodb.resources | indent 8 }}
  {{- end }}
  {{- if (empty .Values.persistence.stash.restore.snapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-init
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.mongodb.type }}
      {{- if (or (eq .Values.service.mongodb.type "LoadBalancer") (eq .Values.service.mongodb.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.mongodb.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: mongodb
          port: 27017
          targetPort: mongodb
          {{- if (and (eq .Values.service.mongodb.type "NodePort") (not (empty .Values.service.mongodb.nodePorts.mongodb))) }}
          nodePort: {{ .Values.service.mongodb.nodePorts.mongodb }}
          {{- end }}
  updateStrategy:
    type: {{ (eq .Values.config.updateStrategy "Recreate") | ternary "RollingUpdate" .Values.config.updateStrategy }}
  terminationPolicy: {{ .Values.config.mongodb.terminationPolicy }}
{{- if .Values.persistence.stash.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: kubedb.com/mongodb
  version: {{ .Values.config.mongodb.version | quote }}
  clientConfig:
    service:
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
      port: 27017
      scheme: mongodb
  parameters:
    kind: MongoDB
    apiVersion: kubedb.com/v1alpha1
    {{- if .Values.config.mongodb.replicaSet.enabled }}
    replicaSets:
      host-0: rs0/{{ template "<%- _.kebabCase(name) %>.mongodb-server" . }}
    {{- end }}
{{- if (not (empty .Values.persistence.stash.restore.snapshot)) }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: MongoDB
spec:
  driver: Restic
  task:
    name: mongodb-restore-{{ index .Values.config.mongodb.versionMap .Values.config.mongodb.version }}
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb
  rules:
    - snapshots:
      - {{ .Values.persistence.stash.restore.snapshot | quote }}
{{- end }}
{{- end }}
{{- end }}
