{{- if (and .Values.config.mysql.internal .Values.config.phpmyadmin.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-phpmyadmin
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-phpmyadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.phpmyadmin.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.phpmyadmin.type }}
  {{- if (or (eq .Values.service.phpmyadmin.type "LoadBalancer") (eq .Values.service.phpmyadmin.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.phpmyadmin.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: container
      {{- if (and (eq .Values.service.phpmyadmin.type "NodePort") (not (empty .Values.service.phpmyadmin.nodePorts.http))) }}
      nodePort: {{ .Values.service.phpmyadmin.nodePorts.http }}
      {{- end }}
  selector:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-phpmyadmin
    release: {{ .Release.Name }}
{{- end }}
