apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(workload.name) %>
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.<%- workload.name %>.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.<%- workload.name %>.type }}
  {{- if (or (eq .Values.service.<%- workload.name %>.type "LoadBalancer") (eq .Values.service.<%- workload.name %>.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.<%- workload.name %>.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ (and (eq .Values.service.<%- workload.name %>.type "LoadBalancer") (not (empty .Values.service.<%- workload.name %>.ports.http))) | ternary .Values.service.<%- workload.name %>.ports.http "80" }}
      targetPort: container
      {{- if (and (eq .Values.service.<%- workload.name %>.type "NodePort") (not (empty .Values.service.<%- workload.name %>.ports.http))) }}
      nodePort: {{ .Values.service.<%- workload.name %>.ports.http }}
      {{- end }}
  selector:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(workload.name) %>
    release: {{ .Release.Name }}
