{{- if .Values.config.redis.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "<%- name %>.fullname" . }}-redis
  labels:
    app: {{ template "<%- name %>.name" . }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: container
  selector:
    app: {{ template "<%- name %>.name" . }}-redis
    release: {{ .Release.Name }}
{{- end }}
