{{- if .Values.persistence.velero.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.persistence.velero.schedule | quote }}
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    ttl: {{ .Values.persistence.velero.ttl | quote }}
---
apiVersion: replicator.siliconhills.dev/v1alpha1
kind: Replicator
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-backup
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-backup
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
 from:
   apiVersion: velero.io/v1
   kind: Schedule
   name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
   namespace: {{ .Release.Namespace }}
 to:
   name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}.{{ .Release.Namespace }}
   namespace: velero
{{- end }}
