{{- if .Values.persistence.stash.enabled }}<% if (hasData) { %>
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-data
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-data
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  wipeOut: false
  backend:
    storageSecretName: {{ .Values.persistence.stash.secret | quote }}
    {{ .Values.persistence.stash.type }}:
      {{- if (or (eq "gcs" .Values.persistence.stash.type) (eq "s3" .Values.persistence.stash.type)) }}
      bucket: {{ .Values.persistence.stash.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.stash.type) }}
      endpoint: {{ .Values.persistence.stash.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.stash.type) }}
      container: {{ .Values.persistence.stash.container | quote }}
      {{- end }}
      prefix: '{{ .Values.persistence.stash.prefix }}/{{ .Release.Namespace }}/data'
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-data
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-data
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-data
  paused: {{ .Values.persistence.stash.paused }}
  schedule: {{ .Values.persistence.stash.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.persistence.stash.keepLast }}
    prune: true
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(name) %>
    volumeMounts:
      - name: data
        mountPath: /_data
    paths:
      - /_data<% } for (var i = 0; i < databases.length; i++) { database = databases[i]; if (database.name !== 'redis') { %>
{{- if (and .Values.config.<%- _.kebabCase(database.name) %>.internal (not (and (eq .Values.config.<%- _.kebabCase(database.name) %>.terminationPolicy "Pause") .Values.config.<%- _.kebabCase(database.name) %>.pause))) }}<% if (hasData || i > 0) { %>---<% } %>
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(database.name) %>
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(database.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  wipeOut: false
  backend:
    storageSecretName: {{ .Values.persistence.stash.secret | quote }}
    {{ .Values.persistence.stash.type }}:
      {{- if (or (eq "gcs" .Values.persistence.stash.type) (eq "s3" .Values.persistence.stash.type)) }}
      bucket: {{ .Values.persistence.stash.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.stash.type) }}
      endpoint: {{ .Values.persistence.stash.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.stash.type) }}
      container: {{ .Values.persistence.stash.container | quote }}
      {{- end }}
      prefix: '{{ .Values.persistence.stash.prefix }}/{{ .Release.Namespace }}/<%- _.kebabCase(database.name) %>-{{ index .Values.config.<%- _.kebabCase(database.name) %>.versionMap .Values.config.<%- _.kebabCase(database.name) %>.version }}'
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(database.name) %>
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-<%- _.kebabCase(database.name) %>
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  repository:
    name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(database.name) %>
  paused: {{ .Values.persistence.stash.paused }}
  schedule: {{ .Values.persistence.stash.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.persistence.stash.keepLast }}
    prune: true
  target:
    ref:
      apiVersion: apps/v1
      kind: AppBinding
      name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-<%- _.kebabCase(database.name) %>
  task:
    name: '<%- _.kebabCase(database.name) %>-backup-{{ index .Values.config.<%- _.kebabCase(database.name) %>.versionMap .Values.config.<%- _.kebabCase(database.name) %>.version }}'
{{- end }}<% }} %>
{{- end }}
