apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: default
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: ['']
    resources:
      - secrets
      - statefulsets
    verbs:
      - get
      - create
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
      - patch
  - apiGroups:
      - stash.appscode.com
    resources:
      - repositories.stash.appscode.com
      - repositories
    verbs:
      - get
      - create
  - apiGroups: ['']
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
