apiVersion: v1
kind: Secret
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:<% for (var i = 0; i < configSecrets.length; i++) { configSecret = configSecrets[i]; %>
  <%- _.snakeCase(configSecret.key) %>: {{ .Values.config.<%- _.camelCase(configSecret.key) %> | quote }}<% } -%>
<%- include('./secret/databases'); %>
