{{- if .Values.config.mongodb.internal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongodb-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.config.mongodb.password | b64enc }}
  username: {{ "root" | b64enc }}
{{- end }}
