apiVersion: v1
kind: Secret
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-postgres-auth
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-postgres-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.config.postgres.password | b64enc }}
  POSTGRES_USER: {{ "postgres" | b64enc }}
