{{- if (and .Values.config.mongodb.internal .Values.config.mongoExpress.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongo-express
  labels:
    app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongo-express
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongo-express
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "<%- _.kebabCase(name) %>.name" . }}-mongo-express
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: lifecycle
                    operator: In
                    values:
                      - spot
      containers:
        - name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongo-express
          image: {{ .Values.images.mongoExpress.repository }}:{{ .Values.images.mongoExpress.tag }}
          imagePullPolicy: {{ .Values.images.mongoExpress.pullPolicy }}
          ports:
            - name: container
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
                  key: mongodb_server
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
                  key: mongo_express_username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}
                  key: mongo_express_password
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
                  key: username
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
                  key: password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "<%- _.kebabCase(name) %>.fullname" . }}-mongodb-auth
                  key: password
          livenessProbe:
            exec:
              command: ['sh', '-c', "wget localhost:8081 2>&1 | grep 'HTTP/1.1 401 Unauthorized'"]
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            exec:
              command: ['sh', '-c', "wget localhost:8081 2>&1 | grep 'HTTP/1.1 401 Unauthorized'"]
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
