{{- if .Values.ingress.phpmyadmin.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "<%- name %>.fullname" . }}-phpmyadmin
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.phpmyadmin.tls }}
    {{- if (empty .Values.ingress.phpmyadmin.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.phpmyadmin.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "<%- name %>.name" . }}-phpmyadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.phpmyadmin.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.phpmyadmin.path }}
            backend:
              serviceName: {{ template "<%- name %>.fullname" . }}-phpmyadmin
              servicePort: http
  {{- if .Values.ingress.phpmyadmin.tls }}
  tls:
    - secretName: {{ template "<%- name %>.phpmyadmin_certificate" . }}
      hosts:
        - {{ .Values.ingress.phpmyadmin.hostname }}
  {{- end }}
{{- end }}
